### ISSUE TITLE
distutils not working for python 3.12

### ISSUE THREAD

**Issue by scaverod** [mork-optimization/mork#227]
The automatic selector of instance is not working since distutils  can not be installed with python version 3.12. 

See: https://docs.python.org/3.10/library/distutils.html

**Comment by rmartinsanta** [comment]
According to [PEP 0632](https://peps.python.org/pep-0632/), `distutil` was deprecated and has been removed in Python 3.12. The instance selector has multiple dependencies that are still using distutil, so we have to wait until this is fixed upstream. For the time being, users should use Python version 3.11 or older.

TODO:
- [ ] Identify which of our dependencies are still relying on distutil.
- [ ] Track upstream releases and upgrade when fixed.

**Comment by rmartinsanta** [comment]
@scaverod this should have been fixed by dedf8e560d950d8dc6601fb227e38f8304d1ef00, can you retest if it works for you now?

You may need to overwrite files in src/main/resources/instance-selector with the ones available at https://github.com/mork-optimization/mork/tree/master/template/src/main/resources/instance-selector
